
### Request specific user
GET {{apiUrl}}/users/{{adminUserId}}
x-auth-token: {{adminToken}}

### Request all users
GET {{apiUrl}}/users
x-auth-token: {{adminToken}}

### Failed login
POST {{apiUrl}}/users/login
Accept: application/json
Content-Type: application/json

{
    "email":"aaa@b.co",
    "password": "1234567"
}

### Register

POST {{apiUrl}}/users
Content-Type: application/json

{
  "name": {
    "first": "Bobby",
    "last": "Dollar"
  },
  "phone": "0512345567",
  "email": "bdollar@ethereal.com",
  "password": "{{password}}",
  "address": {
    "country": "Israel",
    "city": "Anytown",
    "street": "Anystreet",
    "houseNumber": 1,
    "zip": 8920435
  },
  "isBusiness": true,
  "image": {}
}

### Login
POST {{apiUrl}}/users/login
Content-Type: application/json

{
    "email": "bdollar@ethereal.com",
    "password": "{{password}}"
}